### ISSUE TITLE
Database ada dimana?

### ISSUE THREAD

**Issue by dashkiwing0** [Maritho/hmvc-ci#1]
Bang database-nya ada dmn?

**Comment by Maritho** [comment]
maaf ya kemaren lupa, di versi 1.1 sudah ada fitur migrasi,

silahkan migrasi dari CLI atau kamu bisa hapus

`if (is_cli() == FALSE) {
            show_404();
  }`

pada Class Migrate di  application/controllers/Migrate.php supaya bisa akses dari browser
